FROM ros:kilted-ros-core

SHELL ["/bin/bash", "-lc"]

WORKDIR /root/workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
  git \
  build-essential \
  cmake \
  pkg-config \
  python3-dev \
  python3-pip \
  python3-rosdep \
  python3-colcon-common-extensions \
  python3-vcstool \
  python3-catkin-pkg \
  python3-empy \
  python3-lark \
  python3-yaml \
  python3-serial \
  python3-transforms3d \
  python3-numpy \
  ros-kilted-rmw-zenoh-cpp \
  ros-kilted-ros2bag \
  ros-kilted-tf2-tools \
  ros-kilted-tf-transformations \
  ros-kilted-teleop-twist-keyboard \
  && rm -rf /var/lib/apt/lists/*
