/**:
  ros__parameters:
    base_frame: world
    tool_frame: tool0

    move_action: /move_action
    group_name: ur_manipulator
    planner_id: RRTConnect
    pipeline_id: ompl
    planning_attempts: 10
    allowed_planning_time: 5.0
    velocity_scaling: 0.2
    acceleration_scaling: 0.2
    position_tolerance: 0.001
    orientation_tolerance: 0.01

    gripper_action: /gripper_controller/gripper_cmd
    gripper_body_close_position: 0.011
    gripper_sensor_close_position: 0.016
    gripper_open_position: 0.006

    image_topic: /camera/camera/color/image_raw


pick_pipe:
  ros__parameters:
    zone_pose_csv: /home/sonieth2/vzlet_ur3e/ws/zone_poses_floor.csv

    velocity_scaling: 0.5
    acceleration_scaling: 0.1

    add_ground_plane: true
    ground_plane_z: -0.05
    ground_plane_thickness: 0.04

    camera_frame: camera_color_optical_frame

    yolo_vote_frames: 2
    yolo_vote_max_center_dist_px: 5.0
    yolo_vote_min_conf: 0.89
    yolo_vote_frame_timeout_s: 3.0
    yolo_vote_debug_dir: vote_detect

    fx: 602.873352
    fy: 600.606750
    cx: 304.549032
    cy: 269.791445

    yolo_model_path: /home/sonieth2/vzlet_ur3e/ws/models/vzlet_ver7.pt

    z_offset_body: 0.165
    z_offset_sensor_pick: 0.15
    z_offset_sensor_place: 0.18

    gripper_max_effort: 0.0


trajectory_teleop_commander:
  ros__parameters:
    servo_topic: /servo_node/delta_twist_cmds
    linear_speed: 0.4
    publish_rate: 30.0

    controller_switch_service: /controller_manager/switch_controller
    trajectory_controller: joint_trajectory_controller
    servo_controller: forward_position_controller
    controller_switch_timeout: 5.0

    servo_command_type_service: /servo_node/switch_command_type
    servo_command_type: 1

    output_dir: dataset_output